### ISSUE TITLE
usun to

### ISSUE THREAD

**Issue by inzynierr** [OnlyBis/memexurer#1]
prosze

**Comment by sadcenter** [comment]
daj bordery

**Comment by inzynierr** [comment]
od razu erhc-sectors

**Comment by sadcenter** [comment]
czemu nie?

**Comment by ticzuu** [comment]
ads:FKjhserglo;jhp:LihgjQEAP"TUI(_QP#(U562-039uR513 V]\BRI
q#> VtpojG{}VhnpoeasJPASE}GO(UJEWGTuaspseuifjpsae;otgujewsptgyospsorgjs;orghujsrtgp[easutgjspfgoujsaef

**Comment by OnlyBis** [comment]
nie usune

**Comment by Memexurer** [comment]
zatwierdzam

**Comment by ticzuu** [comment]
super

**Comment by OnlyBis** [comment]
:biblethump:

**Comment by OnlyBis** [comment]
asdfjklsd hjkfhjkfd sklhjasfd hkljfasd hkljsfakld hjhjfs dhlkj fdahfad kjlsfd kljlkhjfdshkjl fdsklhjdfs dfskhjafhjkld slhkjfsd hksfd jkhfd sahljkafsd khjl fasdhlfd skd lhafhljkds alhkjfd akhjf dshlfhksld j flkdl fasdkh fsalhdkhfkls dajhlkfs hkljdfkfjd shkjfs djkhfsd hkjfd shkjfd shkjfhjkd skfhjd shkjfd shkjfd skjhflsd alhkjfd hjfklsadvxbzc,nmvb,nmzcx bnm,vxcz,bnmvcxzb bnm, v c bn vcmbncvbnxmbvxmcnvbmncweoriiuoweruiodxhkj hk fhkj khfjxcbv ksdfjlkjlk fjlkwjlkwej

**Comment by sadcenter** [comment]
tak

**Comment by OnlyBis** [comment]
zamykamy?!??!?!?!?!??!?!?

**Comment by Memexurer** [comment]
tak

**Comment by OnlyBis** [comment]
nieee

**Comment by OnlyBis** [comment]
@Memexurer kiedy dasz lobby????????

**Comment by ticzuu** [comment]
@OnlyBis kto ma ten  ma

**Comment by OnlyBis** [comment]
tak

**Comment by inzynierr** [comment]
dobra debilu usuwaj to a nie
